[package]
name = "avail-subxt"
version = "0.1.0"
authors = ["Luka Borkovic <luka.borkovic@ethernal.tech>"]
edition = "2021"


[dependencies]
subxt = "0.24.0"
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive", "full", "bit-vec"] }
serde = { version = "1.0", features = ["derive"] }
parity-util-mem = "0.11.0"
scale-info = { version = "2.0.0", features = ["bit-vec"] }
derive_more = "0.99.17"
structopt = "0.3.25"
anyhow = "1.0.66"

[dev-dependencies]
async-std = { version = "1.9.0", features = ["attributes", "tokio1"] }
sp-keyring = "6.0.0"
futures = "0.3.13"

[features]
default = ["api-dev"]
api-dev = []
api-main = []

[workspace]
