name: Polygon Avail Releaser
on: push

jobs:
  release_awx:
    runs-on: ubuntu-latest
    container:
      image: amd64/centos:centos7
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
         - uses: actions/checkout@v2
         - name: install cargo deps and build avail
           run: |
            cat /etc/os-release
            yum install git -y
            yum install centos-release-scl -y
            yum install llvm-toolset-7 -y
            yum install gcc-c++ -y
            scl enable llvm-toolset-7 bash
            yum whatprovides *libclang.so
